<?php

namespace AppBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPostsGroupByYear(){

        $queryBuilder= $this->createQueryBuilder("p");

        $queryBuilder->select("YEAR(p.createdAt)as yearPublished,
                                      COUNT(p.id) as numberOfPosts")
            ->groupBy("yearPublished");

        return $queryBuilder->getQuery()->getArrayResult();

    }

    public function getPostsByYear($year){

        // je récupère une instance du querry builder
        $qb = $this->createQueryBuilder("p");

        $qb ->select("p")
            ->where("YEAR(p.createdAt)=:year")
            ->setParameter("year", $year);

        return $qb->getQuery()->getResult();

    }
}
