<?php

namespace AppBundle\Repository;

/**
 * ThemeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThemeRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllThemes(){
        //méthode integrée a EntityRepository
        $queryBuilder= $this->createQueryBuilder('t');
        $queryBuilder->select("t.name,count(p) as numberOfPosts, t.id" )
        ->innerJoin("t.posts","p")
        ->groupBy("t.id");

        dump($queryBuilder->getDQL());

        return $queryBuilder->getQuery();

    }
}
