<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Post;

/**
 * ThemeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThemeRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllThemes(){
       $qb = $this->createQueryBuilder('t');
       $qb->select("t.name, count(p.id) as numberOfPosts, t.id")
       ->innerJoin("t.posts", "p")
       ->groupBy("t.id");

       dump($qb->getDQL());

       return $qb->getQuery();
    }
}
