# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
              users:
                admin:
                  password: $2y$15$TnfApdKyysFV3t0WXxdbc.a.AxUgljBIp.XmKdgo5CucIYOj96CPq
                  roles: ["ROLE-SUPER_ADMIN","ROLE_ADMIN"]
        author_provider:
          entity:
            class: AppBundle:Author
            property: email

    encoders:
      Symfony\Component\Security\Core\User\User:
        algorithm: bcrypt
        cost: 15

      AppBundle\Entity\Author: plaintext
        #algorithm: sha1



    role-hierarchy:
      ROLE_SUPER_ADMIN: ROLE_ALLOWED_TO_SWITCH

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        #toute route contenant admin passera par ce firewall et passera par le provider cité pour aller chercher les informations
        admin_login:
          pattern: ^/admin/login$
          anonymous: ~


        admin_firewall:
          pattern: ^/admin
          provider: in_memory
          form_login:
            login_path: admin_login
            check_path: admin_login_check
            default_target_path: admin_home
          logout:
            path: admin_logout
            target: homepage

        main:
            anonymous: true
            pattern: ^/
            provider: author_provider
            form_login:
                login_path: author_login
                check_path: author_login_check
                default_target_path: homepage
            logout:
                path: author_logout
                target: homepage
            # activate different ways to authenticate

            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            #form_login: ~

    access-control:
      - {path: ^/admin/secure, role: ROLE_SUPER_ADMIN }